name: hark
on:
  push:
    paths:
      - LICENSE.txt

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v1
    - name: ter
      uses: lhotari/action-upterm@v1
      #uses: owenthereal/action-upterm@v1
